[build]
  command = "npm ci && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

  # Neon Database environment variables
  # These should be set in your Netlify site settings
  NEON_HOST = "ep-xxx.us-east-1.neon.tech"
  NEON_DATABASE = "neondb"
  NEON_USERNAME = "your_username"
  NEON_PASSWORD = "your_password"

# SPA fallback (no API redirects needed for frontend-only app)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
